name: PR Title Lint (Conventional Commits)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  pr_title_lint:
    name: Lint pull request title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # needed if comment: true
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          comment: true
          token: ${{ secrets.GITHUB_TOKEN }}
